Update README.md
givebk/public pull request #1
Opened 2022-04-25 13:26 UTC by nthypes

2022-04-25 14:33 UTC, mfrma-moura requested changes
just a test

2022-04-25 14:33 UTC, mfrma-moura commented on CODEOWNERS
> +*       @givebk-bot
just a test

2022-04-25 19:39 UTC, nthypes commented
@givebk-bot !target $100

2022-04-26 01:56 UTC, nthypes commented
@givebk-bot !pledge $0.20

2022-04-26 03:57 UTC, closed without merging